#!/usr/bin/env bash
curl 'https://gateway.****.com/SendSmsGet.aspx' -G \
--data-urlencode "user=******" \
--data-urlencode "password=******" \
--data-urlencode "to=${2}" \
--data-urlencode "text=${1}"
